### ISSUE TITLE
Question about Normalization for haas_score Calculation

### ISSUE THREAD

**Issue by shujuecn** [vggls/medical_xai#1]
I am truly grateful for the code you've provided.

When training the model, I used the following Normalize parameters:

```python
transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.225, 0.225, 0.225])
```
When calculating the haas_score, do I also need to normalize it to [-1, 1] first?

**Comment by vggls** [comment]
Hi @shujuecn . 
haas_score value is by definition in [-1,1]; "1" due to the "min" and "-1" due to the "max", regardless of the training transformation. Quoting the original paper "To support highlighting as well as de-emphasizing, we normalize both an input (x_Norm) and a heatmap (h_Norm) at the range of −1 to +1."
